   +-----------------+           +-------------------+
   |    Person       |           |  PersonController |
   +-----------------+           +-------------------+
   | - _id: ObjectId |           | - get all users() |
   | - name: String  |           | - createPerson()  |
   | - ...           |           | - getPersonById() |
   |                 |           | -updatePersonById()|
   |                 |           | -deletePersonById()|
   +-----------------+           +-------------------+
                                 
   +-----------------+          +--------------------+
   | Express App     |          |     Mongodb        | 
   +-----------------+  |       +--------------------+
   | - Define routes |          |StorePresonRequest  |
   | - Middleware    |          |FetchPersonRequest  |
   | - Database conn |          |UpdatePersonRequest |
    +-----------------+         |DeletePersonRequest |
                                +--------------------+
